server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lyb123
    url: jdbc:mysql://localhost:3306/pay_develop?characterEncoding=utf8&useSSL=false
    #    使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      max-active: 20
      initial-size: 3
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  cache:
    jcache:
      config: classpath:ehcache.xml

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1ms
#        min-idle: 0

    timeout: 0ms

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
    port: 5672

# 数据库配置
mybatis:
  mapper-locations: classpath:pojo/dtm/mapping/*.xml
  type-aliases-package: com.pay.pojo.dtm
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql
mapper:
  mappers: com.pay.database.mybatis.config.BaseMapper
  identity: MYSQL

pay:
  dictionary:
    package:
      valuePackageName: com.pay.beans.dictionary.view
      dataPackageName: com.pay.beans.dictionary.data
      mytest: com.test